---

 - name: Create Service Directory
   file:
     path: "{{ item }}"
     owner: pankaj
     group: pankaj
     recurse: yes
     state: directory
     mode: '0774'
   with_items:
     - "{{ home_dir }}/Setup"

 - name: Create Log Directories
   file:
      path: "{{ home_dir }}/logs"
      state: directory
      mode: '0777'
      owner: pankaj
      group: pankaj

 - name: Download and Unrachive Artifcats
   unarchive:
     src: "{{ python_app_package }}"
     dest: "{{ home_dir }}/Setup"
     owner: pankaj
     group: pankaj
     mode: '774'
   notify:
    - Update Supervisor
 - name: Create Supervisor Config
   template:
     src: app_template.j2
     dest: "{{ home_dir }}/supervisor.conf"
     mode: '0774'
     owner: pankaj
     group: pankaj
   notify:
     - Update Supervisor
